### ISSUE TITLE
支持导出html格式

### ISSUE THREAD

**Issue by bleedingsaber** [wvit/web-document#3]
您好，一直想找一款将网页保存为html格式的插件，类似浏览器的‘save as’功能，但现在大多网站都做了屏蔽，很难用浏览器的‘save’把网页保存完整，只需保留网站文字和格式排版，图片还用网站原来的地址，即使原网站图片挂了，还有文字就行，因为大部分图片都没什么用。其实功能类似SingleFile，但不下载图片，图片还保留原网站地址，但是SingleFile的作者拒绝了这一需求（ https://github.com/gildas-lormeau/SingleFile/issues/1217 ）。为什么不用SingleFile，保存的文件太大了，很多时候保存的文件大小，甚至超过保存为PDF格式，而且用的时间越长，小文件堆积起来，也是一个很大的文件夹。

不知道您是否愿意实现这样的功能？找了很久也没找到类似插件。

**Comment by wvit** [comment]
我明白你的需求了，你是希望我提供一个npm包，还是将这个功能集成在我的 web-document 插件中

**Comment by wvit** [comment]
我明白你的需求了，你是希望我在单独提供一个按钮“导出html文件”，还是直接将这个功能直接集成在 web-document 插件保存的页面中

**Comment by bleedingsaber** [comment]
感谢快速回复！
两者都可以，单独提供按钮，直接将网页导出html，或者先到web-document库，再多选，统一导出，对我来说，两种方法都可以。只要能在设置中自由选择，保存网页时是否下载原图片，如果选择不下载图片，就保留图片网址，以后用浏览器打开，原图片网址能用，就打开图片，原图片网址失效，也不影响看文字。

**Comment by wvit** [comment]
> 感谢快速回复！ 两者都可以，单独提供按钮，直接将网页导出html，或者先到web-document库，再多选，统一导出，对我来说，两种方法都可以。只要能在设置中自由选择，保存网页时是否下载原图片，如果选择不下载图片，就保留图片网址，以后用浏览器打开，原图片网址能用，就打开图片，原图片网址失效，也不影响看文字。

这个功能我可以调研一下怎么添加，如果技术上没问题我将在下一个版本添加上，因为我也使用 SingleFile 的底层库。
但是我有一个问题：
想一些技术博客，游游

**Comment by wvit** [comment]
> 感谢快速回复！ 两者都可以，单独提供按钮，直接将网页导出html，或者先到web-document库，再多选，统一导出，对我来说，两种方法都可以。只要能在设置中自由选择，保存网页时是否下载原图片，如果选择不下载图片，就保留图片网址，以后用浏览器打开，原图片网址能用，就打开图片，原图片网址失效，也不影响看文字。

这个功能我可以调研一下怎么添加，如果技术上没问题我将在下一个版本添加上，因为我也使用 SingleFile 的底层库。

**Comment by wvit** [comment]
你好，此功能已在 https://github.com/wvit/web-document/releases/tag/v1.2.0 “偏好设置”中添加了，正在向chorme web store 提交审核。

需要注意的是，你如果要重新安装插件，记得将已保存的页面文档进行导出，避免丢失已保存的页面文档数据。

如果有问题可以继续反馈，如果愿意在 chrome web store 提交一个5星评价再好不过了。

**Comment by wvit** [comment]
你好，此功能已在 https://github.com/wvit/web-document/releases/tag/v1.2.0 “偏好设置”中添加了，正在向chorme web store 提交审核。

需要注意的是，你如果要重新安装插件，记得将已保存的页面文档进行导出，避免丢失已保存的页面文档数据。

有问题可以继续反馈，如果愿意在 chrome web store 提交一个5星评价那就再好不过了。

**Comment by bleedingsaber** [comment]
hi，图片的设置找到了，导出可否加个html格式，json格式好是好，就是不够通用。还是我操作有问题，没找到导出html格式。

**Comment by wvit** [comment]
> hi，图片的设置找到了，导出可否加个html格式，json格式好是好，就是不够通用。还是我操作有问题，没找到导出html格式。

你好，如果加一个导出为HTML文件的话，似乎与 SingleFile的功能重叠了。
其实我这个插件的使用场景是将页面保存为能直接在浏览器中查看的本地文档，方便检索和避免打开过多标签页等。

**Comment by wvit** [comment]
> hi，图片的设置找到了，导出可否加个html格式，json格式好是好，就是不够通用。还是我操作有问题，没找到导出html格式。

我考虑一下，这个功能以什么样的形式加上。

**Comment by wvit** [comment]
你好，在v1.2.1 版本已支持导出为 html zip文件功能，https://github.com/wvit/web-document/releases/tag/v1.2.1

（如果要重新安装插件，记得将已保存的页面文档进行导出，避免丢失已保存的页面文档数据）

**Comment by bleedingsaber** [comment]
非常感谢，晚上回去试一下哈！
